version: 2
updates:
- package-ecosystem: npm
  directory: "/_yarn"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - growse
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - growse
