---
queue_rules:
  - name: default
    conditions:
      - "check-success=Build"

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "check-success=Build"
      - files~=blog/(\d{4})
    actions:
      queue:
        name: default
        method: rebase
