language: ruby
cache: bundler

git:
  depth: 5

before_install:
- sudo apt-get install -y debsigs
- echo $DEBSIGN | base64 -d | gpg --import

script:
- bundle exec jekyll b
- ./fpm.sh -s dir -t deb -n growse-com-jekyll --description "growse.com static content" --url https://www.growse.com/ --prefix /var/www/ -p _site -a noarch  -v 1.0.1-$TRAVIS_BUILD_NUMBER _site/=growse-jekyll
- debsigs --sign=origin --default-key=63F29D43F8F9E605 _site/growse-com-jekyll_1.0.1-"$TRAVIS_BUILD_NUMBER"_all.deb

after_success:
- bundle exec deb-s3 upload --s3-region=eu-west-1 --suite stable --origin "Andrew Rowson" --sign=63F29D43F8F9E605 --bucket apt-growse-com _site/growse-com-jekyll_1.0.1-"$TRAVIS_BUILD_NUMBER"_all.deb
