title: growse.com Pointless musings
email: $"RFC3696"IS\\Best RFC=hurray@growse.com
description: >
  DESCRIPTIONG
baseurl: ""
url: "https://www.growse.com"

assets:
  digest: true
  compress:
    js: true
    css: true
  autosize: true
  sources:
    - _assets/css
    - _assets/fonts
    - _assets/images
    - _assets/videos
    - _assets/javascript
    - _assets/video
    - _assets/image
    - _assets/img
    - _assets/js

monthly_archive:
  path: "/archive"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - "*.iml"
  - vendor
  - .idea

permalink: /:year/:month/:day/:title:output_ext