title: growse.com Pointless musings
email: $"RFC3696"IS\\Best RFC=hurray@growse.com
description: >
  DESCRIPTIONG
baseurl: ""
url: "https://www.growse.com"

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "assets/fonts"
    values:
      font: true
  - scope:
      path: "assets/*.js"
    values:
      js: true
  - scope:
      path: "assets/css/*.css"
    values:
      css: true
monthly_archive:
  path: "/archive"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-image-size
exclude:
  - Gemfile
  - Gemfile.lock
  - "*.iml"
  - vendor
  - .idea
  - _yarn
  - searchIndex
  - searchIndexServer

permalink: /:year/:month/:day/:title:output_ext
