version: 1

update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
      - growse
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
  - package_manager: "javascript"
    directory: "/_yarn"
    update_schedule: "live"
    default_reviewers:
      - growse
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"