name: Build, package and upload
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - uses: actions/setup-node@v1
        with:
          node-version: '12'  
      - name: Install gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Build web assets
        run: |
          yarn install
          yarn run build
        working-directory: _yarn
      - name: Build Jekyll
        run: bundle exec jekyll b
      - name: Upload site
        uses: actions/upload-artifact@v1
        with:
          name: site-dir
          path: _site/
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v1
      - name: Download site artifact
        uses: actions/download-artifact@v1
        with:
          name: site-dir
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Install fpm
        env:
          BUNDLE_GEMFILE: Gemfile.deploy
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Make deb package
        env:
          BUNDLE_GEMFILE: Gemfile.deploy
        run: bundle exec fpm -s dir -t deb --deb-priority optional --maintainer github@growse.com --vendor github@growse.com -n growse-com-jekyll --description "growse.com static content" --url https://www.growse.com/ --prefix /var/www/ -p site-dir -a noarch  -v 1.0.2-$GITHUB_RUN_NUMBER site-dir/=growse-jekyll
      - name: Upload to Apt repo
        env:
          KEY_PASSPHRASE: ${{ secrets.DEBSIGN_KEY_PASSPHRASE }}
          APT_CREDENTIALS: ${{ secrets.APT_CREDENTIALS }}
        run: |
          echo $APT_CREDENTIALS > aptly-auth
          find -maxdepth 1 -name "*.deb" -exec curl --netrc-file aptly-auth -XPOST -F file=@{} https://apttoo.growse.com/api/files/blog \;
          curl --netrc-file aptly-auth -X POST https://apttoo.growse.com/api/repos/defaultrepo/file/blog
          curl --netrc-file aptly-auth -X PUT https://apttoo.growse.com/api/publish/:./stablish
