name: Build, package and upload
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
        working-directory: blog/_yarn
      - uses: actions/cache@v3
        name: Yarn cache restore
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/cache@v3
        name: Ruby gems cache restore
        id: rubygems-cache
        with:
          path: blog/vendor/bundle
          key: ${{ runner.os }}-gems-v2-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-v2
      - uses: actions/cache@v3
        name: Go modules cache restore
        id: golang-cache
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3
          bundler-cache: true
      - uses: actions/setup-node@v3
        with:
          node-version: '12'
      - name: Install gems
        working-directory: ./blog
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle
        env:
          BUNDLE_PATH: vendor/bundle
      - name: Build
        run: make build
      - uses: superfly/flyctl-actions@1.3
        if: github.event_name == 'push'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy"        
